apiVersion: v1
kind: Namespace
metadata:
  name: financial
  labels:
    app.kubernetes.io/managed-by: skaffold
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: financial-monitoring
  labels:
    app.kubernetes.io/managed-by: skaffold
